export type CountryPreset = {
  country: string
  phoneCountryCode: string
  currencyCode: string
  locale: string
  language: string
  timezone: string
  stateLabel: string
  cityLabel: string
  postalCodeLabel: string
}

export const COUNTRY_OPTIONS = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const

export const REGION_LABEL_OPTIONS = [
  "State / Province",
  "State",
  "Province",
  "Region",
  "County",
  "Department",
  "Governorate",
  "Prefecture",
  "Parish",
  "Emirate",
] as const

export const CITY_LABEL_OPTIONS = [
  "City",
  "Town",
  "Municipality",
  "District",
  "Village",
] as const

export const COUNTRY_PRESETS: CountryPreset[] = [
  { country: "Australia", phoneCountryCode: "+61", currencyCode: "AUD", locale: "en-AU", language: "en", timezone: "Australia/Sydney", stateLabel: "State", cityLabel: "City", postalCodeLabel: "Postcode" },
  { country: "Bangladesh", phoneCountryCode: "+880", currencyCode: "BDT", locale: "bn-BD", language: "en", timezone: "Asia/Dhaka", stateLabel: "Division", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Belgium", phoneCountryCode: "+32", currencyCode: "EUR", locale: "fr-BE", language: "fr", timezone: "Europe/Brussels", stateLabel: "Region", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Brazil", phoneCountryCode: "+55", currencyCode: "BRL", locale: "pt-BR", language: "en", timezone: "America/Sao_Paulo", stateLabel: "State", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Canada", phoneCountryCode: "+1", currencyCode: "CAD", locale: "en-CA", language: "en", timezone: "America/Toronto", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "China", phoneCountryCode: "+86", currencyCode: "CNY", locale: "zh-CN", language: "en", timezone: "Asia/Shanghai", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Egypt", phoneCountryCode: "+20", currencyCode: "EGP", locale: "ar-EG", language: "ar", timezone: "Africa/Cairo", stateLabel: "Governorate", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Ethiopia", phoneCountryCode: "+251", currencyCode: "ETB", locale: "am-ET", language: "en", timezone: "Africa/Addis_Ababa", stateLabel: "Region", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "France", phoneCountryCode: "+33", currencyCode: "EUR", locale: "fr-FR", language: "fr", timezone: "Europe/Paris", stateLabel: "Region", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Germany", phoneCountryCode: "+49", currencyCode: "EUR", locale: "de-DE", language: "en", timezone: "Europe/Berlin", stateLabel: "State", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Ghana", phoneCountryCode: "+233", currencyCode: "GHS", locale: "en-GH", language: "en", timezone: "Africa/Accra", stateLabel: "Region", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "India", phoneCountryCode: "+91", currencyCode: "INR", locale: "en-IN", language: "en", timezone: "Asia/Kolkata", stateLabel: "State", cityLabel: "City", postalCodeLabel: "PIN code" },
  { country: "Indonesia", phoneCountryCode: "+62", currencyCode: "IDR", locale: "id-ID", language: "en", timezone: "Asia/Jakarta", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Ireland", phoneCountryCode: "+353", currencyCode: "EUR", locale: "en-IE", language: "en", timezone: "Europe/Dublin", stateLabel: "County", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Israel", phoneCountryCode: "+972", currencyCode: "ILS", locale: "he-IL", language: "en", timezone: "Asia/Jerusalem", stateLabel: "District", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Italy", phoneCountryCode: "+39", currencyCode: "EUR", locale: "it-IT", language: "en", timezone: "Europe/Rome", stateLabel: "Region", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Japan", phoneCountryCode: "+81", currencyCode: "JPY", locale: "ja-JP", language: "en", timezone: "Asia/Tokyo", stateLabel: "Prefecture", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Jordan", phoneCountryCode: "+962", currencyCode: "JOD", locale: "ar-JO", language: "ar", timezone: "Asia/Amman", stateLabel: "Governorate", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Kenya", phoneCountryCode: "+254", currencyCode: "KES", locale: "en-KE", language: "en", timezone: "Africa/Nairobi", stateLabel: "County", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Kuwait", phoneCountryCode: "+965", currencyCode: "KWD", locale: "ar-KW", language: "ar", timezone: "Asia/Kuwait", stateLabel: "Governorate", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Malaysia", phoneCountryCode: "+60", currencyCode: "MYR", locale: "ms-MY", language: "en", timezone: "Asia/Kuala_Lumpur", stateLabel: "State", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Mexico", phoneCountryCode: "+52", currencyCode: "MXN", locale: "es-MX", language: "en", timezone: "America/Mexico_City", stateLabel: "State", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Morocco", phoneCountryCode: "+212", currencyCode: "MAD", locale: "fr-MA", language: "fr", timezone: "Africa/Casablanca", stateLabel: "Region", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Netherlands", phoneCountryCode: "+31", currencyCode: "EUR", locale: "nl-NL", language: "en", timezone: "Europe/Amsterdam", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "New Zealand", phoneCountryCode: "+64", currencyCode: "NZD", locale: "en-NZ", language: "en", timezone: "Pacific/Auckland", stateLabel: "Region", cityLabel: "City", postalCodeLabel: "Postcode" },
  { country: "Nigeria", phoneCountryCode: "+234", currencyCode: "NGN", locale: "en-NG", language: "en", timezone: "Africa/Lagos", stateLabel: "State", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Pakistan", phoneCountryCode: "+92", currencyCode: "PKR", locale: "en-PK", language: "en", timezone: "Asia/Karachi", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Philippines", phoneCountryCode: "+63", currencyCode: "PHP", locale: "en-PH", language: "en", timezone: "Asia/Manila", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Qatar", phoneCountryCode: "+974", currencyCode: "QAR", locale: "ar-QA", language: "ar", timezone: "Asia/Qatar", stateLabel: "Municipality", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Rwanda", phoneCountryCode: "+250", currencyCode: "RWF", locale: "en-RW", language: "en", timezone: "Africa/Kigali", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Saudi Arabia", phoneCountryCode: "+966", currencyCode: "SAR", locale: "ar-SA", language: "ar", timezone: "Asia/Riyadh", stateLabel: "Region", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Sierra Leone", phoneCountryCode: "+232", currencyCode: "SLE", locale: "en-SL", language: "en", timezone: "Africa/Freetown", stateLabel: "District", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Singapore", phoneCountryCode: "+65", currencyCode: "SGD", locale: "en-SG", language: "en", timezone: "Asia/Singapore", stateLabel: "Region", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "South Africa", phoneCountryCode: "+27", currencyCode: "ZAR", locale: "en-ZA", language: "en", timezone: "Africa/Johannesburg", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "South Korea", phoneCountryCode: "+82", currencyCode: "KRW", locale: "ko-KR", language: "en", timezone: "Asia/Seoul", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Spain", phoneCountryCode: "+34", currencyCode: "EUR", locale: "es-ES", language: "en", timezone: "Europe/Madrid", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Sri Lanka", phoneCountryCode: "+94", currencyCode: "LKR", locale: "en-LK", language: "en", timezone: "Asia/Colombo", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Sweden", phoneCountryCode: "+46", currencyCode: "SEK", locale: "sv-SE", language: "en", timezone: "Europe/Stockholm", stateLabel: "County", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Switzerland", phoneCountryCode: "+41", currencyCode: "CHF", locale: "de-CH", language: "en", timezone: "Europe/Zurich", stateLabel: "Canton", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Tanzania", phoneCountryCode: "+255", currencyCode: "TZS", locale: "en-TZ", language: "en", timezone: "Africa/Dar_es_Salaam", stateLabel: "Region", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Thailand", phoneCountryCode: "+66", currencyCode: "THB", locale: "th-TH", language: "en", timezone: "Asia/Bangkok", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Turkey", phoneCountryCode: "+90", currencyCode: "TRY", locale: "tr-TR", language: "en", timezone: "Europe/Istanbul", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Uganda", phoneCountryCode: "+256", currencyCode: "UGX", locale: "en-UG", language: "en", timezone: "Africa/Kampala", stateLabel: "Region", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "United Arab Emirates", phoneCountryCode: "+971", currencyCode: "AED", locale: "ar-AE", language: "ar", timezone: "Asia/Dubai", stateLabel: "Emirate", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "United Kingdom", phoneCountryCode: "+44", currencyCode: "GBP", locale: "en-GB", language: "en", timezone: "Europe/London", stateLabel: "County", cityLabel: "City", postalCodeLabel: "Postcode" },
  { country: "United States", phoneCountryCode: "+1", currencyCode: "USD", locale: "en-US", language: "en", timezone: "America/New_York", stateLabel: "State", cityLabel: "City", postalCodeLabel: "ZIP code" },
  { country: "Vietnam", phoneCountryCode: "+84", currencyCode: "VND", locale: "vi-VN", language: "en", timezone: "Asia/Ho_Chi_Minh", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Zambia", phoneCountryCode: "+260", currencyCode: "ZMW", locale: "en-ZM", language: "en", timezone: "Africa/Lusaka", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
  { country: "Zimbabwe", phoneCountryCode: "+263", currencyCode: "USD", locale: "en-ZW", language: "en", timezone: "Africa/Harare", stateLabel: "Province", cityLabel: "City", postalCodeLabel: "Postal code" },
] as const

export function getCountryPreset(country: string | null | undefined) {
  const normalized = (country || "").trim().toLowerCase()
  return COUNTRY_PRESETS.find((preset) => preset.country.toLowerCase() === normalized) || null
}
